### ISSUE TITLE
Improvements we could make to wp scaffold package-readme?

### ISSUE THREAD

**Issue by danielbachhuber** [aaemnnosttv/wp-cli-valet-command#1]
Are there improvements we could make to `wp scaffold package-readme` so you could continue to use it to support the README.md format you prefer as you proceed with the project?

**Comment by aaemnnosttv** [comment]
I used `scaffold package`, is the readme produced by this command the same?  I added to the generated file but I think that's kind of expected.  It's pretty good as-is I think.

**Comment by danielbachhuber** [comment]
> is the readme produced by this command the same?

Yes, `wp scaffold package-readme` is called as a part of `wp scaffold package`.

> I added to the generated file but I think that's kind of expected. It's pretty good as-is I think.

Something else to be aware of is that if you add the `commands` declaration to your `composer.json`:

https://github.com/wp-cli/scaffold-package-command/blob/master/composer.json#L14-L20

The command will generate usage docs from your command docs, like so:

https://github.com/wp-cli/scaffold-package-command#using

**Comment by aaemnnosttv** [comment]
Let's continue this convo on the other repo 👍
