### ISSUE TITLE
add --path support

### ISSUE THREAD

**Issue by djdesign** [aaemnnosttv/wp-cli-valet-command#10]
Would love to see argument `--path=`  support added to project.

**Comment by aaemnnosttv** [comment]
Hey there.  I didn't realize that it wasn't supported at current since it's a global flag, but I can see why it might not be working as expected.  I'll take a look.

**Comment by djdesign** [comment]
It works as expected. Thank you for the additional statement for `--in=` since valets site name is the folder name.
