### ISSUE TITLE
DB error Warning: mysqli_real_connect(): (HY000/2002) valet bedrock installation

### ISSUE THREAD

**Issue by djdesign** [aaemnnosttv/wp-cli-valet-command#13]
Unable to configure or login into the website with the current package or wpcli version. Attempted basic install of `wp valet` command that works as expected, bedrock project does not.

Any ideas or suggestions?

**WP-CLI Version***:  .24-.26alpha
*_tested stable branch to nightly updates_
**Package**: aaemnostvv/wp-cli-valet-command
**Package Version**: commit 5637efc
**MYSQL**:  Ver 15.1 Distrib 10.1.16-MariaDB, for osx10.11 (x86_64) using readline 5.1
**Composer**: version 1.2.2 2016-11-03 17:43:15
**OS:**: macOS Sierra 10.12.2

[Terminal Log Error Output](https://gist.github.com/djdesign/657393cda23d07c2525a54565a26be3e)

**Comment by aaemnnosttv** [comment]
Any reason why you're running the command from the package's source directory?

```
Error: Warning: mysqli_real_connect(): (HY000/2002): No such file or directory in /Users/DJ/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/demo/web/wp/wp-includes/wp-db.php on line 1529
Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /Users/DJ/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/demo/web/wp/wp-includes/wp-db.php on line 1559
Warning: mysql_connect(): No such file or directory in /Users/DJ/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/demo/web/wp/wp-includes/wp-db.php on line 1559
Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down.
```

Try running the command again with the `--debug` flag, and post what you get there.

**Comment by djdesign** [comment]
I apologize did not see your comment before further debugging on my own.

Ended up completely removing & reinstalling WP-CLI with packages all had I previously installed.
After the reinstall, everything seems to be running as expected. If I run into this again I will report the debug log here.

**Comment by aaemnnosttv** [comment]
Glad to hear all is well!
