### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by fabianhenzler** [aaemnnosttv/wp-cli-valet-command#14]
```
➜  ~ wp package install aaemnnosttv/wp-cli-valet-command
Installing package aaemnnosttv/wp-cli-valet-command (dev-master)
Updating /Users/fabianhenzler/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 860160 bytes) in phar:///usr/local/bin/wp/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php on line 388

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 860160 bytes) in phar:///usr/local/bin/wp/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php on line 388
```

Sorry for the noob question - but what can I do? :)

**Comment by fabianhenzler** [comment]
increased memory_limit to 512M

**Comment by infotexture** [comment]
@fabianhenzler I'm getting the same error.

Where do I change the memory limit as you suggested?

**Comment by christianmagill** [comment]
Where did you go to increase the memory limit?

**Comment by christianmagill** [comment]
Found it /usr/local/etc/php/7.1/php.ini

**Comment by aaemnnosttv** [comment]
Related wp-cli/wp-cli#3629, wp-cli/wp-cli#3533, and [more](https://github.com/wp-cli/wp-cli/issues?utf8=%E2%9C%93&q=is%3Aissue%20exhausted)

**Comment by seothemes** [comment]
For me this was in /usr/local/etc/php/7.0/conf.d/php-memory-limits.ini

**Comment by andfinally** [comment]
To find the location of your `php.ini`:

```
php -r 'phpinfo();' | grep 'php.ini'
```

h/t Chris Ruppel 
https://apple.stackexchange.com/questions/31816/how-can-i-increase-command-line-memory-limit-for-php-with-mamp-pro

**Comment by aaemnnosttv** [comment]
To determine what your current memory limit is:

```
php -i | grep memory_limit
```

To find your ini files:

```
php --ini
```

**Comment by andfinally** [comment]
Woah thank you, much better than my answer!

**Comment by LC43** [comment]
since wp cli uses php-cli, its enough to change php-cli settings.

**Comment by tonyclemmey** [comment]
I had to increase the memory limit even higher than 512m to work.

Changing the file at /usr/local/etc/php/7.3/php.ini made no difference and the correct file was at /usr/local/etc/php/7.3/conf.d/php-memory-limits.ini as mentioned by @seothemes 

```
Tonys-MacBook-Pro:valet tony$ valet restart
Restarting php...
Restarting nginx...
Valet services have been restarted.
Tonys-MacBook-Pro:valet tony$ php -i | grep memory_limit
memory_limit => 1024M => 1024M
Tonys-MacBook-Pro:valet tony$ wp package install aaemnnosttv/wp-cli-valet-command:^1.0
```

**Comment by yashodhank** [comment]
```
Example: php -d memory_limit=512M "$(which wp)" package install wp-cli/admin-command
```
