### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by fabianhenzler** [aaemnnosttv/wp-cli-valet-command#16]
When I try to access /wp-admin I get a 404 "File not found."
![scr_2016-12-14_03-19-08_pm](https://cloud.githubusercontent.com/assets/1168345/21185380/bb378f72-c210-11e6-95ff-da196bbc6501.png)

Here is the NGINX config and 
![scr_2016-12-14_03-20-18_pm](https://cloud.githubusercontent.com/assets/1168345/21185418/d54ad82e-c210-11e6-8e4a-eee164f2fb52.png)

[nginx-error.log.zip](https://github.com/aaemnnosttv/wp-cli-valet-command/files/651955/nginx-error.log.zip)
[matrix42.dev.zip](https://github.com/aaemnnosttv/wp-cli-valet-command/files/651957/matrix42.dev.zip)

**Comment by aaemnnosttv** [comment]
See laravel/valet#236

;)
