### ISSUE TITLE
add option to install plugins/themes

### ISSUE THREAD

**Issue by kotfarepra** [aaemnnosttv/wp-cli-valet-command#17]
Hello 
Great work so far. 
Would be great if we can also add/remove plugins/themes and also the --extra-config that WP CLI supports 

Regards

**Comment by aaemnnosttv** [comment]
Hi there and thanks for your kind words!

That's an interesting idea, I wonder what that might look like.

Have you seen [Dictator](https://github.com/danielbachhuber/dictator)?

Sounds like you could probably get much more than you're asking for with one more command after the initial creation.

**Comment by kotfarepra** [comment]
Hi
Checked that Dictator and seems too much of a pain for a "quick wp spin"

just having some more CLI parameters like 
wp valet new blog --enable-debug --plugins=woocommerce --themes=twentythirteen 

So it would 
-- enable debug 
-- install the plugins listed ( and deactivate/remove the hello dolly )
-- install the theme and activate it  

If you check my gists i have 2-3 examples but they are in bash/powershell

**Comment by aaemnnosttv** [comment]
I'm hesitant to add something like this if most users aren't going to use it.

The `--enable-debug` flag or similar is a good idea. I'll think about it.

**Comment by djdesign** [comment]
I agree with you @aaemnnosttv.  It should be kept as a separate process, as users have many different ways of installing their plugins etc.

**Comment by aaemnnosttv** [comment]
Passing on this one for now.
