### ISSUE TITLE
Certificates are not being created

### ISSUE THREAD

**Issue by fabianhenzler** [aaemnnosttv/wp-cli-valet-command#18]
I always end up with an empty certificates folder and therefore not running https://XY.dev
```
nginx: [emerg] BIO_new_file("/Users/me/.valet/Certificates/XY.dev.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/Users/me/.valet/Certificates/XY.dev.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
```

I'm just running ` wp valet new XY --locale=en_US --dbprefix=XY_` which has been worling before

**Comment by aaemnnosttv** [comment]
Can you provide a bit more information about your environment please?

```
wp --info
valet --version
```

**Comment by fabianhenzler** [comment]
Hi,

➜  Sites wp --info
PHP binary:	/usr/local/Cellar/php71/7.1.2_13/bin/php
PHP version:	7.1.2
php.ini used:	/usr/local/etc/php/7.1/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/Users/fabianhenzler/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.1.0
➜  Sites valet --version
Laravel Valet 2.0.3


after reinstalling `wp-cli-valet-command` it works
