### ISSUE TITLE
Feature request: clone command

### ISSUE THREAD

**Issue by nickdavis** [aaemnnosttv/wp-cli-valet-command#20]
This is great, thank you so much for creating it.

Was wondering if a `clone` command might be something that could be added in a future version?

For example, from your parent directory containing all your site folders you could do something like:

`wp valet clone old-site-folder new-site-folder`

And then it would make an exact copy of the `old-site-folder` and replicate it at `new-site-folder`, apart from the database which it would copy but apply the `new-site-folder.dev` URL too instead.

What do you think?

**Comment by aaemnnosttv** [comment]
This is an interesting idea, thanks for the suggestion!

My initial thought to it is that it is probably a bit trickier to implement than you might think.  Keep in mind that the command supports installing different WordPress projects (see the `project` flag).

By copying over the original version, we would need to perform some some surgery on the configuration file to replace the DB name (what if the db name and the db user are the same?). We would also need to run a search & replace on the new site to update the site urls, etc to use the new site.

We would probably want/need a way to exclude certain files or directories from the clone, and possibly other exceptions.

Not impossible, but might be more trouble than it's worth.  I'll think about it and see if it seems like something that might get used. It might be a better fit as its own command.

I think the idea of creating a new site from a _template_ definitely could be valuable. Whether that template is an existing install or not is another story ;)

**Comment by nickdavis** [comment]
Hey @aaemnnosttv, thanks for the reply.

Yes, I think in my initial enthusiasm I slightly underestimated the complexity of a `clone` feature :)

I think you've actually summed it up better than me with the template idea though, that could be really useful.

**Comment by srikat** [comment]
I've just put together a shell script for this.

1. Create a file named say, `wp-clone` in ~/bin.

2. In ~/.bash_profile, add `export PATH="$PATH:$HOME/bin"` to add to system's PATH variable.

3. In `wp-clone` place

```
#!/usr/bin/env /bin/bash

# change current directory to Sites
cd ~/Sites/

# create destinaton directory
mkdir $2

# copy files from source to destination
cp -a $1/. $2

# export source db
cd $1
wp db export $1.sql

# navigate to destination
cd ~/Sites/$2

# change db name to wp_<destination site name> in wp-config.php 
search=wp_$1
replace=wp_$2
sed -i '' "s/${search}/${replace}/g" wp-config.php

# create db from values in wp-config.php
wp db create

# import source db
wp db import ~/Sites/$1/$1.sql

# find and replace URLs
wp search-replace $1.dev $2.dev

# secure the site
valet secure $2

# launch the site in default browser 👊
valet open $2
```

Change all instances of `Sites` to the name of your sites folder.

Assumes that your db names are in this format: `wp_sitename`. If not, adjust accordingly.

**Comment by aaemnnosttv** [comment]
Closing this for now. May revisit the template idea later if there's more interest.
Thanks for the script @srikat !

**Comment by nickdavis** [comment]
Here's my slightly revised version, one year+ on. The main change is using wp cli to update the cloned site `DB_NAME` value in `wp-config.php`.

```
#!/usr/bin/env /bin/bash

# change current directory to Sites
cd ~/Sites/

# create destinaton directory
mkdir $2

# copy files from source to destination
cp -a $1/. $2

# export source db
cd $1
wp db export $1_clone.sql

# navigate to destination
cd ~/Sites/$2

# change db name to wp_<destination site name> in wp-config.php
wp config set DB_NAME $2

# create db from values in wp-config.php
wp db create

# import source db
wp db import ~/Sites/$1/$1_clone.sql

# delete source db export file
rm ~/Sites/$1/$1_clone.sql

# find and replace URLs
wp search-replace //$1.test //$2.test

# secure the site
valet secure $2

# launch the site in default browser 👊
valet open $2
```

Thanks @srikat for the original!

**Comment by benjaminluoma** [comment]
Thank you @nickdavis and @srikat. This is supa hot. Works great ;-)

@aaemnnosttv of course thank you too. This is a real game changer for me. 

+1 site cloning - I use the same starter theme and set of plugins AND starter content so cloning the site files and db saves soooo much time.

You all are heroes ;-)
