### ISSUE TITLE
Feature Request: Honour the settings in config.yml

### ISSUE THREAD

**Issue by Luminus** [aaemnnosttv/wp-cli-valet-command#28]
The `wp valet new` command currently ignores the `~/.wp-cli/config.yml` file since defaults are already set for the command.

Is there a way to have it honour the settings in that file that I've missed?

If there isn't, would we consider adding a `--config` flag that accepts a boolean, where `true` would cause it to grab values from the config file hierarchy of `wp-cli.local.yml`, 
`wp-cli.yml file` and `~/.wp-cli/config.yml` or at least from the last one since it provides global settings?

**Comment by aaemnnosttv** [comment]
Hi there. I'm having trouble reproducing this myself.

In my `~/.wp-cli/config.yml` file, I've added the following lines:

```yml
valet new:
  unsecure: true
```

This works as expected for me by not configuring newly created sites to use https.

Would you please elaborate on what you're trying to do that isn't working as expected? Also, please provide the output of `wp --info` here as well.

**Comment by Luminus** [comment]
I have this in my `~/.wp-cli/config.yml`

,,,
core install:
  admin_user: luminus
  admin_password: password
  admin_email: luminus@randompreoject.test
,,,

These options are used when I run `wp core install` but when I run `wp valet new` they are ignored in favour of the defaults that the WP CLI Valet command has set.

**Comment by aaemnnosttv** [comment]
Ah, I see what you mean now.

You could achieve this now by defining these in your `config.yml` like so:

```yml
valet new:
  admin_user: luminus
  admin_password: password
  admin_email: luminus@randompreoject.test
```

I understand you want to be able to use your defaults for the underlying `wp` commands executed by `valet new`, but I'm not sure there is a good way to add support for this as the options are all defined at the `new` command-level.

**Comment by Luminus** [comment]
Awesome. I'll take it.

Can I make the admin email project specific within the `config.yml` file with something like

```yml
admin_email: luminus@{project}.test
```
Or would that be bash scripting territory?

**Comment by Luminus** [comment]
I'm also running into another challenge.

I can download WP without the default themes and plugins using `wp core download` with this in my `config.yml`:

```yml
core download:
  skip-content: true
```

When I modify the `valet new` section of my `config.yml` file with the snippet below, though, `wp valet new` fails with `Error: Skip content build is only available for the latest version.`

```yml
valet new:
  skip-content: true
```

**Comment by Luminus** [comment]
Updating the wp-cli core-command by running `wp package install git@github.com:wp-cli/core-command.git` fixed it.

Thanks @aaemnnosttv.
