### ISSUE TITLE
Env Variable for Project

### ISSUE THREAD

**Issue by Log1x** [aaemnnosttv/wp-cli-valet-command#29]
Any possibility when you push a little update to this at some point you could add an env variable for setting a default project? I'd like to default to Bedrock. :)

Thanks a lot for your CLI stuff.

**Comment by aaemnnosttv** [comment]
Thanks man. Have you considered configuring your default using your global wp-cli config (usually at `~/.wp-cli/config.yml`)?

You should be able to accomplish this already by adding the following:

```yml
valet new:
  project: bedrock
```

I would be open to considering the env var if there was a good reason why the above wouldn't work.

**Comment by Log1x** [comment]
Didn't even know `config.yml` was a thing. This did the trick. Thanks!

**Comment by aaemnnosttv** [comment]
https://make.wordpress.org/cli/handbook/config/#config-files 😉
