### ISSUE TITLE
valet new with dbprefix option does not work for Bedrock installs

### ISSUE THREAD

**Issue by cyrilkas** [aaemnnosttv/wp-cli-valet-command#32]
When I create a Bedrock project with the command `wp valet new my-project --dbprefix=mywp_ --project=bedrock` my tables are still with default `wp_` prefix.
Any clues ?

**Comment by aaemnnosttv** [comment]
Hey, thanks for bringing this to my attention. This currently isn't implemented for Bedrock installs. The valet command translates DB configuration into values in the `.env` file which we generate from the `.env.example` which comes with the project. The optional `DB_PREFIX` is actually a more recent addition to the example file so I think it just wasn't there when support for Bedrock was originally added.

Should have a fix for this one soonish, but you're welcome to try your hand at a PR too :)

**Comment by cyrilkas** [comment]
Hi ! Thanks for your reply.
I've created a commit (my first!) change to `BedrockInstaller`. It's works !
