### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by marcosdipaolo** [aaemnnosttv/wp-cli-valet-command#34]
I just reinstalled wp-cli and it works globally. 
Now intalling wp valet i get this error:
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in phar:///usr/local/bin/wp/vendor/composer/composer/src/Composer/Json/JsonFile.php on line 270`

I tried with ` php --ini ` to know my ini and `php -i | grep memory_limit` to modify to 512M the memory_limit but **after modifying it and restarting** (*is it needed?*) still i get memory_limit : 128M

**Comment by marcosdipaolo** [comment]
found it: 
the problem wasnt at `/usr/local/etc/php/7.2/php.ini` but at : `/usr/local/etc/php/7.2/conf.d/php-memory-limits.ini` which looked like this: 
`; Max memory per instance
memory_limit = 512M

;The maximum size of an uploaded file.
upload_max_filesize = 128M

;Sets max size of post data allowed. This setting also affects file upload. To upload large files, this value must be larger than upload_max_filesize
post_max_size = 128M
`
Changed the memory_limit and thats it

**Comment by samtheson** [comment]
Great! Maybe close the issue then?

**Comment by brandonpittman** [comment]
Yeah, I had this same issue. Might be nice if there was a mention about the possibility of running into this somewhere in the README.
