### ISSUE TITLE
cURL error 28

### ISSUE THREAD

**Issue by brandonpittman** [aaemnnosttv/wp-cli-valet-command#35]
```sh
wp valet new site
Don't go anywhere, this should only take a second...
Error: Failed to get url 'https://api.wordpress.org/core/version-check/1.6/?locale=en_US': cURL error 28: Connection timed out after 10000 milliseconds.
```
Keep getting this error every time I try to spin up an install of a site. If I added the `--project=bedrock` flag, then it just never finishes *or* spits out any errors.

**Comment by JiveDig** [comment]
@brandonpittman I'm hitting this too. Did you find a fix?

**Comment by brandonpittman** [comment]
@jivedig yep, I stopped using Wordpress
