### ISSUE TITLE
Error with MySQL 8.0 on macOS / Homebrew (and solution)

### ISSUE THREAD

**Issue by greatislander** [aaemnnosttv/wp-cli-valet-command#37]
When setting up Valet and using this command on macOS High Sierra, I ran into an issue I hadn't encountered before with Homebrew's install of MySQL 8.0. When running:

```
wp valet new mysite
```

I got this error:

```
Don't go anywhere, this should only take a second...
Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down.
```

Digging deeper I got this error when trying to connect to the database with Sequel Pro:

```
Authentication plugin 'caching_sha2_password' cannot be loaded: dlopen(/usr/local/lib/plugin/caching_sha2_password.so, 2): image not found
```

Turns out that `mysql_native_password` authentication needs to be enabled for each MySQL user, so the [following fix](https://taruchan.com/2018/06/22/cant-connect-to-mysql-from-sequel-pro/) solved the issue and restored the `wp valet` command's normal functionality.

1. Connect to MySQL via the command line: `mysql -uroot`
2. Execute the following command: `update mysql.user set plugin = 'mysql_native_password';`
3. Exit the MySQL prompt: `exit`
4. Restart the Homebrew MySQL service: `brew service restart mysql`

I think this might be good to add to the wiki, but otherwise feel free to just close the issue and others can hopefully benefit from the snag I ran into with this.

**Comment by aaemnnosttv** [comment]
Thanks for the detailed report and the solution!

I don't think there's anything needed on the command side here but it's good to have if someone else comes looking with the same problem.

**Comment by emilas44** [comment]
This didn't work for me. I had to add this line:
`default_authentication_plugin=mysql_native_password`
inside this file:
`/usr/local/etc/my.cnf`

**Comment by EdgarOReyes** [comment]
thank you so much!
