### ISSUE TITLE
Latest dev-master Valet breaks new installs

### ISSUE THREAD

**Issue by aaemnnosttv** [aaemnnosttv/wp-cli-valet-command#39]
This only applies to those using the latest version (dev-master) laravel/valet@23e2eee8a126d0c8a4472b7c6bee86e38c6f09d0 or later.

As of laravel/valet#241 the `valet domain` no longer outputs the bare TLD, and instead outputs a more informational message which breaks the value used for the command.

```
$ wp valet new example
Don't go anywhere, this should only take a second...
Error: The 'admin@example.Valet is configured to serve for TLD: .test' email address is invalid.
```

**Comment by drbyte** [comment]
You can fix this in a non-breaking way by updating 
https://github.com/aaemnnosttv/wp-cli-valet-command/blob/master/src/Process/SystemValet.php

by rewriting the `domain()` method like this:

```php
    public function domain()
    {
        $result = $this->run('domain')->stdout);
        // get just the tld suffix from the response
        preg_match('/(?:\.?)([\S]*)*$/', $result, $matches);
        return trim($matches[0], '.');
    }
```

**Comment by drbyte** [comment]
See PR #40
