### ISSUE TITLE
New command downloads WP on every install

### ISSUE THREAD

**Issue by aaemnnosttv** [aaemnnosttv/wp-cli-valet-command#4]
When running `valet new` with the `--debug` flag, we can see that the majority of the time it takes to create a new install is spent running `wp core download`.  

This should not be the case for successive installs with the same WordPress version, as WP-CLI caches core download (and others), but for some reason it is not using the cached file when we are calling `core download` within the `new` command.

The desired behavior can be seen when running `wp core download` directly:  "Using cached file...".

**Comment by aaemnnosttv** [comment]
@danielbachuber does this warrant an issue with WP-CLI or am I doing something wrong?

**Comment by danielbachhuber** [comment]
> This should not be the case for successive installs with the same WordPress version, as WP-CLI caches core download (and others), but for some reason it is not using the cached file when we are calling core download within the new command.

I _think_ this is because you're launching a new process, `$HOME` isn't set for that process, and as such, the cache directory doesn't get written to.

> does this warrant an issue with WP-CLI or am I doing something wrong?

If the actual issue is my hypothesis, then the general purpose solution is https://github.com/wp-cli/wp-cli/issues/3139.

**Comment by aaemnnosttv** [comment]
`run_command` didn't work for me either.  I went with the latter and it worked!
