### ISSUE TITLE
Command asking for Password

### ISSUE THREAD

**Issue by polishedwp** [aaemnnosttv/wp-cli-valet-command#49]
When I use wp-cli-valet, either as a simple command OR in a script, it always at some point asks for the `sudo` password, pausing with this prompt:
`Password:`

I am using the following command:

`wp valet new sitename --dbuser=user --dbpass=password `

I have verified this behavior on 2 systems, MacOS and Linux/Ubuntu. 

I can use the following commands using WP-CLI with no password interruptions.
 
`wp core download`

`wp core config --dbname=wp_test --dbuser=root --dbpass=root --dbhost=localhost --dbprefix=wp_`

`wp db create`

`wp core install --url=test.test --title=Website-Name --admin_user=admin --admin_password=admin --admin_email=email@example.com`

Is this normal behavior? How can it be avoided to streamline the install process?

**Comment by aaemnnosttv** [comment]
The underlying wp-cli commands do not require a sudo password, but some valet commands do (eg. creating and trusting a self-signed ssl certificate).

For example, if you create a new site with `wp valet new mysite --unsecure` I bet you will not be prompted for a password.

Laravel Valet stores a token (or otherwise stores the authentication provided by your password) to only require it once.

Try running `valet trust` to generate the necessary files for Valet to run its commands without requiring a password every time.

Give that a try and let me know if that helps.

**Comment by polishedwp** [comment]
Thank you so much for the detail explanation. You were absolutely correct, running `wp valet new mysite --unsecure` did not prompt for a password. 

I did run `valet trust` and it stored the necessary authentication. I can now run my install script with no prompts:

```
#!/bin/bash
# Ref wp-cli-valet - https://github.com/aaemnnosttv/wp-cli-valet-command

#styles
VP_NONE='\033[00m'
VP_RED='\033[01;31m'
VP_GREEN='\033[01;32m'
VP_YELLOW='\033[01;33m'
VP_PURPLE='\033[01;35m'
VP_CYAN='\033[01;36m'
VP_WHITE='\033[01;37m'
VP_BOLD='\033[1m'
VP_UNDERLINE='\033[4m'

# Update default core install
echo -e "${VP_GREEN}UPDATING DEFAULT WP CORE"
cd ~/Sites/default
wp core update 

# Update default core install
echo -e "\n"
echo -e "${VP_GREEN}UPDATING DEFAULT wp plugins"
cd ~/Sites/default/wp-content/plugins
wp plugin update --all

# change current directory to Sites
cd ~/Sites/
echo -e "\n"
echo -e "${VP_PURPLE}MAKE directories for $1"

# create WordPress site  
wp valet new $1 --dbname="wp_$1" --dbuser="root" --dbpass="root" --dbprefix="wp_" --admin_user="admin-user" --admin_password="admin-pass" --admin_email="user@email.local"

# site creation success message
echo -e "\n"
echo -e "${VP_CYAN}Success $1 created ... moving to Add-ins"

# Navigate to themes directory
echo -e "\n"
echo -e "${VP_PURPLE}Installing custom themes."
cd ~/Sites/
cd $1/wp-content/themes

# copy all the content from default themes
cp -a ~/Sites/default/wp-content/themes/. ~/Sites/$1/wp-content/themes

# update parent Genesis theme
wp theme update genesis

# activate Genesis Sample
wp theme activate genesis-sample

# site creation success message
echo -e "\n"
echo -e "${VP_YELLOW}Success Themes loaded"

# Copy plugins my default
echo -e "\n"
echo -e "${VP_WHITE}Installing Plugins"
cp -Rp ~/Sites/default/wp-content/mu-plugins/ ~/Sites/$1/wp-content/mu-plugins/
cp -Rp ~/Sites/default/wp-content/plugins/ ~/Sites/$1/wp-content/plugins/

# delete Hello Dolly 😕
echo -e "\n"
echo -e "${VP_YELLOW}Goodbye Dolly"
wp plugin delete hello

# activate all plugins
echo -e "\n"
echo -e "${VP_RED}Activating Plugins"
wp plugin activate --all

echo -e "\n"
echo -e "${VP_RED}Deactivating 2 Plugins"
wp plugin deactivate wordpress-importer
wp plugin deactivate akismet
echo -e "${VP_RED}Deactivating plugins complete"

# delete 2016 themes 🙄
echo -e "\n"
echo -e "${VP_CYAN}Delete Old Themes"
wp theme delete twentysixteen

# launch the frontend site in default browser 👊
# valet open $1

# launch the new site admin/backend in the default browser 
open "https://${1}.test/wp-admin"
```

**Comment by aaemnnosttv** [comment]
Glad to hear it! Cheers
