### ISSUE TITLE
Edit the config.yml to include more option

### ISSUE THREAD

**Issue by coolwebs** [aaemnnosttv/wp-cli-valet-command#50]
Is it possible to edit the config.yml file to include addition install features such as removing "hello dolly" and akismet plugins and setting a particular default theme and removing the others? Perhaps with avail conditions from https://make.wordpress.org/cli/handbook/config/ ?

**Comment by aaemnnosttv** [comment]
Hi there,

New features would require a new release. However, you can currently create new installs without the default content (plugins+themes) via this added configuration in your [config file](https://make.wordpress.org/cli/handbook/config/#config-files):

```yml
core download:
    skip-content: true
```

I may add an option to the `new` command in the future to allow for this on a per-command basis.

Setting a default theme, or adding installing plugins post-creation is something I have to think about as it may be out of scope for the command.

**Comment by aaemnnosttv** [comment]
Closing this as config options aren't separate from command options.
Will consider adding a `--skip-content` or similar option to the `new` command in the future.
