### ISSUE TITLE
Could not open input file

### ISSUE THREAD

**Issue by mattswann** [aaemnnosttv/wp-cli-valet-command#53]
Hi,

I'm getting this error... 

`Debug (aaemnnosttv/wp-cli-valet-command): WP_CLI\ProcessRun Object
(
    [command] => C:/PHP/php C:\Users\Matt Swann\AppData\Roaming\Composer\vendor\wp-cli\wp-cli\php\boot-fs.php core  "download"  --version="latest"
    [stdout] => Could not open input file: C:\Users\Matt
    [stderr] =>
    [cwd] => C:\tools\Cmder/site
    [env] => Array
        (
            [HOME] => C:\Users\Matt Swann
            [PATH] => C:\tools\Cmder\bin;C:\tools\Cmder\vendor\bin;C:\tools\Cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\tools\Cmder\vendor\conemu-maximus5;C:\tools\Cmder\vendor\conemu-maximus5\ConEmu;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Python27\;C:\Python27\Scripts;C:\Python37\Scripts\;C:\Python37\;C:\tools\ruby26\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\ProgramData\ComposerSetup\bin;C:\PHP;C:\PHP\ext;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Users\Matt Swann\.wp-cli;C:\Program Files\MySQL\MySQL Server 8.0;C:\Program Files\MySQL\MySQL Server 8.0\bin;C:\Users\Matt Swann\.wp-cli\packages;C:\Users\Matt Swann\AppData\Local\Microsoft\WindowsApps;C:\tools\Cmder;C:\Users\Matt Swann\AppData\Roaming\npm;C:\Users\Matt Swann\AppData\Local\Yarn\bin;C:\Users\Matt Swann\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\tools\Cmder
            [WP_CLI_PACKAGES_DIR] =>
            [WP_CLI_CONFIG_PATH] =>
        )
    [return_code] => 1
    [run_time] => 0.35121703147888
    [caller] => WP_CLI_Valet\Process\SystemWp
)
 (0.554s)
Error:`

Any clues on how to solve this one? 

Any help would be appreciated.

**Comment by aaemnnosttv** [comment]
I haven't tested it on Windows, but I would imagine there may be problems.

This command is designed as an integration with [Laravel Valet](https://github.com/laravel/valet), a minimal development environment for Mac.
