### ISSUE TITLE
Some .test domains aren't loading (Possible old Trellis interference)

### ISSUE THREAD

**Issue by johnbsingfield** [aaemnnosttv/wp-cli-valet-command#59]
Hello,

I'm having an issue with some <name>.test domain when I create them using `wp valet new <name>`. 

After some thoughts I realized all problematic domain names were those that I also used while experimenting with Trellis. These local Trellis install are long gone by now (in my files and my Virtual Box as well), but somehow, something is interferring with my new valet-managed domains.

Have you ever experienced this? How would I clean this up, in order to be able to use <name>.test again on Valet?

Thanks.

**Comment by aaemnnosttv** [comment]
This sounds like an issue with the domain resolution rather than the valet wp-cli command.

I would check your `/etc/hosts` file for added entries for these domains and remove them as Valet uses dnsmasq to catch all `.test` domains (or whatever your configured TLD is) and route them to localhost.
