### ISSUE TITLE
Error: env: mysql: No such file or directory

### ISSUE THREAD

**Issue by johnbsingfield** [aaemnnosttv/wp-cli-valet-command#61]
Hello everyone,

I am trying to install wp-cli valet command, which I did, but when I run:

`wp valet new example`

I get:

`Error: env: mysql: No such file or directory`

I did try this:

`export PATH=$PATH:/usr/local/mysql/bin`

But it didn't do solve anything. Should I revert/cancel that command? how? And more importantly: how can I make this msql error dissapear?

I am very grateful for your help in advance. Thank you.

**Comment by aaemnnosttv** [comment]
Is mysql installed and running? What do you see if you run `mysql -V` ?

**Comment by johnbsingfield** [comment]
Thanks for the quick reply! When I run the command I get `command not found: mysql`. How can I properly install msql? I'm sorry of being such a debutant.

**Comment by aaemnnosttv** [comment]
Hey, no problem. It sounds like you may need to install Laravel Valet, which is what this command leverages under the hood. See step #1 under the installation instructions here: https://github.com/aaemnnosttv/wp-cli-valet-command#environment-setup

It looks like it may not install MySQL anymore by default, but see the section [linked there](https://laravel.com/docs/6.x/valet#installation) titled "Database" about how to install MySQL. It's pretty straightforward. 

Once you've got that all set up then you should be good to go 👍

**Comment by johnbsingfield** [comment]
I did install Valet sucessfully, as well as MySQL with `brew install mysql@5.7`.

`ping foobar.test` works well and I did park the folder I want to use with wp valet. 

Would it be that command I runned earlier that messed the whole thing up?
`export PATH=$PATH:/usr/local/mysql/bin`

Or maybe it's something else. 🤔

**Comment by johnbsingfield** [comment]
Oh, It works! Actually I had to run `brew install mysql` instead of the `brew install mysql@5.7` listed below in laravel's Valet docs.

Thanks a lot for your help. I love your script! I use it a lot.
