### ISSUE TITLE
Uncaught Error: Class 'Dotenv\Environment\DotenvFactory'

### ISSUE THREAD

**Issue by landerss0n** [aaemnnosttv/wp-cli-valet-command#62]
Hey,

When I try to install a new site I get this error everytime.

```
Don't go anywhere, this should only take a second...

Error: PHP Fatal error:  Uncaught Error: Class 'Dotenv\Environment\DotenvFactory' not found in /Users/lucas/.wp-cli/packages/vendor/illuminate/support/helpers.php:646
Stack trace:
#0 /Users/lucas/Sites/valet/jebygg/config/application.php(39): env('DATABASE_URL')
#1 phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197) : eval()'d code(7): require_once('/Users/lucas/Si...')
#2 phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197): eval()
#3 phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#4 phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#5 phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#6 phar:///usr/local/Cellar/wp-cli/2.4.0/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_ in /Users/lucas/.wp-cli/packages/vendor/illuminate/support/helpers.php on line 646
```

I have tried to reinstall alla wp-cli packages with no success, any ideas?

**Comment by aaemnnosttv** [comment]
Thanks for bringing this to my attention.
Looks like there's a breaking change with the latest Bedrock. I'll follow up on this and get back to you.

**Comment by aaemnnosttv** [comment]
Hey there, this should be fixed now. Just upgrade the command to the latest and you should be good to go 👍

**Comment by dmpinder** [comment]
Hi, I seem to be having the same issue. 

I've run `wp cli update` and `wp package install git@github.com:aaemnnosttv/wp-cli-valet-command.git`, so both are up to date.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/4732147/75490465-2ba98b80-59ac-11ea-9962-14fa85dddec0.png">

However when I run the command to create a new site, I get this error:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/4732147/75490554-4e3ba480-59ac-11ea-8270-afb0d9cb34be.png">

Any idea what this might be?

Thanks!

**Comment by aaemnnosttv** [comment]
Hey @dmpinder - this is strange indeed.

After looking into it a bit, it seems that there may be a discrepancy between what is reported as the latest dependencies by the wp-cli package repository and the vcs/git repo.

When installing the package using the git syntax, the repo is added as a vcs/git repo in the composer.json for wp-cli packages `~/.wp-cli/packages`.

Try editing this file and move the definition for the valet command above the repo for `wp-cli`
![image](https://user-images.githubusercontent.com/1621608/75524537-c63eb480-5a16-11ea-9527-dc0d5951cab8.png)

Once you do that, try installing the package again. If that doesn't work, run a Composer update in your packages directory like so:

```
composer update -d ~/.wp-cli/packages
```

**Comment by dmpinder** [comment]
Hey @aaemnnosttv, thanks for the quick reply!

So I switched the order in composer.json:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/4732147/75543011-d5befd00-5a18-11ea-8aea-eb27a15d82dd.png">

And then tried installing the package again...

<img width="466" alt="image" src="https://user-images.githubusercontent.com/4732147/75543069-f25b3500-5a18-11ea-8de2-a3349030a843.png">

And the repos get switched back to the original position:

<img width="370" alt="image" src="https://user-images.githubusercontent.com/4732147/75543132-0ef76d00-5a19-11ea-8842-6c9dac2c5c73.png">

Unfortunately it didn't solve the problem:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/4732147/75543170-220a3d00-5a19-11ea-98e0-c75901dc83dd.png">

If I run `composer update -d ~/.wp-cli/packages` as suggested, it just comes back with:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/4732147/75543199-32bab300-5a19-11ea-8b1a-f1e6795ca343.png">

And same result trying to install a new site.

**Comment by aaemnnosttv** [comment]
> And the repos get switched back to the original position:

That's odd. In that case, try switching it back with the valet command repo first and update the package using composer directly to update the packages.

```
composer update -d ~/.wp-cli/packages
```

Let me know how this works for you.

I raised this issue with the wp-cli maintainers as well since this appears to be an issue with the core package repo.

**Comment by RomkaLTU** [comment]
I don't know it doesn't resolve this issue for me. Tried removing 

`wp package uninstall aaemnnosttv/wp-cli-valet-command`

and installing again 

`wp package install git@github.com:aaemnnosttv/wp-cli-valet-command.git`

**Comment by aaemnnosttv** [comment]
@RomkaLTU Unfortunately those commands likely won't fix it right now, as you said.

Try the steps outlined here https://github.com/aaemnnosttv/wp-cli-valet-command/issues/62#issuecomment-592412344 without reinstalling the package. Then run composer update as described.

**Comment by aaemnnosttv** [comment]
This should be fixed now. There was an issue with the official wp-cli package index which this command has been on for a long time, but is no longer maintained which was causing stale information about the package to be used when installing/updating.

Please try again and let me know if this is still an issue 👍

**Comment by dmpinder** [comment]
Hey @aaemnnosttv, this is working now! 🎉 

I just ran 

```composer update -d ~/.wp-cli/packages```

and now the site install works. 

Thanks for sorting so quickly! A colleague of mine confirmed the same bug and solution.

**Comment by aaemnnosttv** [comment]
Great, thanks for confirming!

It should be fixed at on the wp-cli package index as well so installing/updating via wp-cli _should work as normal_.

Glad all is back to normal now for you both 😄
