### ISSUE TITLE
Timezone Setting

### ISSUE THREAD

**Issue by neilgee** [aaemnnosttv/wp-cli-valet-command#65]
I was hoping that `--timezone_string="Sydney"` would work by adding it to a creation script,  but it didn't - is it possible to add it?

`wp valet new $1 --version="5.3.2" --locale="en_AU" --timezone_string="Sydney" --dbname="wp_$1" --dbuser="root" --dbpass="" --dbprefix="wp_" --admin_user="admin" --admin_password='password' --admin_email="support@support.com.au" --unsecure
`

**Comment by aaemnnosttv** [comment]
The command mostly interacts with the underlying core commands for `config create` and `core install`, neither of which currently offer an option for the timezone.

You might propose this as a new option (probably to `core install`) to the core command. If core  supports it, I'd be happy to add support for it here 😄

**Comment by neilgee** [comment]
ok thanks will raise an issue there

**Comment by neilgee** [comment]
They are asking what the core command is, have I worded that Incorrect?https://github.com/laravel/valet/issues/948#issuecomment-624696046

**Comment by aaemnnosttv** [comment]
Oh sorry, I meant core as in `wp-cli` which is what would handle anything WP-related like this.

This is the command I would think is the most relevant to add it to:
https://github.com/wp-cli/core-command#wp-core-install

**Comment by neilgee** [comment]
Ah ok, wasn't thinking straight - I just added it to my shell script on site creation and it sets the value, works fine.
`wp option update timezone_string "Australia/Sydney"`
