### ISSUE TITLE
Fatal error: Allowed memory size of 536870912 bytes exhausted

### ISSUE THREAD

**Issue by seothemes** [aaemnnosttv/wp-cli-valet-command#67]
When trying to install we keep hitting this issue:

```shell
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 5242880 bytes) in phar:///usr/local/bin/wp/vendor/composer/composer/src/Composer/DependencyResolver/RuleSet.php on line 90
```

**Comment by seothemes** [comment]
Installing with the following command works:

```shell
php -d memory_limit=1024M "$(which wp)" package install git@github.com:aaemnnosttv/wp-cli-valet-command.git
```

**Comment by aaemnnosttv** [comment]
Yeah, it's a [common issue](https://make.wordpress.org/cli/handbook/common-issues/#php-fatal-error-allowed-memory-size-of-999999-bytes-exhausted-tried-to-allocate-99-bytes) installing just about any package through wp-cli using the default memory limits that come with Brew's PHP.

Glad you were able to get it installed 👍
