### ISSUE TITLE
PHP Undefined index: dbpass … Valet_Command.php … line 191

### ISSUE THREAD

**Issue by djdesign** [aaemnnosttv/wp-cli-valet-command#7]
Ran into the error:
`DJ@server2 ~/s/valet> wp valet new demo
Don't go anywhere, this will only take a second! ....PHP Notice:  Undefined index: dbpass in /Users/DJ/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/Valet_Command.php on line 191

Notice: Undefined index: dbpass in /Users/DJ/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/Valet_Command.php on line 191
.............
Success: demo ready! https://demo.dev`

WP-CLI version:	0.24.1
PHP binary:	/usr/local/Cellar/php71/7.1.0-beta.1_2/bin/php
PHP version:	7.1.0beta1
php.ini used:	/usr/local/etc/php/7.1/php.ini
WP-CLI root dir:	/usr/local/Cellar/wp-cli/0.24.1
WP-CLI packages dir:	/Users/DJ/.wp-cli/packages/
WP-CLI global config:	/Users/DJ/.wp-cli/config.yml
WP-CLI project config:

**Comment by aaemnnosttv** [comment]
Sorry about that.  I plan to have these sort of things covered by tests soon.
