### ISSUE TITLE
Can't pass --dbhost option

### ISSUE THREAD

**Issue by martin-josef** [aaemnnosttv/wp-cli-valet-command#80]
WP CLI Valet is super helpful to me, thanks for creating it. The only issue I've run into so far is I can't pass a different host upon creation. I get: 

```
Error: Parameter errors:
unknown --dbhost parameter
```

It's also not possible for me to add the host to the ~/.wp-cli/config.yml . I can pass other options, no issue there.

Kind regards, 
Martin

**Comment by aaemnnosttv** [comment]
Hi @martin-josef! Support for this option was literally added just yesterday 😄 https://github.com/aaemnnosttv/wp-cli-valet-command/releases/tag/v1.3.0

Please update to the latest and you should be all set 👍

**Comment by martin-josef** [comment]
Ha what a coincidence, I've been using your tool for quite some time, too. Thanks!

**Comment by aaemnnosttv** [comment]
You should be getting v1.3 but the wp-cli package index has a tendency to be out of date for a while now. You can upgrade it using Composer though.

Give this a try:

```
cd ~/.wp-cli/packages
composer config repos.wp-cli --unset
composer update
```

**Comment by martin-josef** [comment]
That worked, thanks!

**Comment by aaemnnosttv** [comment]
Great to hear it! Cheers 👍
