### ISSUE TITLE
Cannot install last version, ReflectionParameter deprecated method error

### ISSUE THREAD

**Issue by SergiArias** [aaemnnosttv/wp-cli-valet-command#83]
Doing `wp package install aaemnnosttv/wp-cli-valet-command:@stable` installs 1.2.1 instead of 1.3.0 thus giving the error
`Deprecated: Method ReflectionParameter::getClass() is deprecated in /Users/.../.wp-cli/packages/vendor/illuminate/container/Container.php on line 811`

I tried to use `wp package install aaemnnosttv/wp-cli-valet-command:1.3.0` but it doesn't allow it for some reason

**Comment by aaemnnosttv** [comment]
Hi there, the problem is due to the wp-cli Composer package index being out of date.

See here for a workaround: https://github.com/aaemnnosttv/wp-cli-valet-command/issues/80#issuecomment-915442448
