### ISSUE TITLE
Place dbhost in wp cli config

### ISSUE THREAD

**Issue by martin-josef** [aaemnnosttv/wp-cli-valet-command#84]
Hello Evan, could you add the option to set the dbhost in the wp cli config file? Thanks for the tool, I use it all the time.

**Comment by aaemnnosttv** [comment]
Hey thanks! Are you referring to this? https://github.com/aaemnnosttv/wp-cli-valet-command#configuring-alternate-defaults You can customize your default `dbhost` in the same way, it just isn't added to the example there yet.

**Comment by martin-josef** [comment]
I apologies, I did put it there, had an error and thought it's related to the dbhost option. Now it works as intended!
