### ISSUE TITLE
Can't install WP / database problem

### ISSUE THREAD

**Issue by verstecken** [aaemnnosttv/wp-cli-valet-command#86]
I spend all night awake trying to make it work.

mariadb, mysql, all the versions, using DBngin - i tried a lot.

I get `Error: env: mysql: No such file or directory` when I create a new site via `wp valet new site`.

I was able to access the database with phpMyAdmin, create an empty database but in the Installation Wizzard of Wordpress I get critical error after entering the DB infos.

Im on macOS 12.1 (Montery) - is this bad?

brew services list gives me error for nginx and masqd.
ping site.test works, I can reach it and click me thru the wizzard until the DB info. There is no further error, only the critical error on your site thing from WP.

Thanks for helping. So excited to use valet with wp-cli-valet-command, although this might not an wp-cli-valet-command issue?!

**Comment by aaemnnosttv** [comment]
Hi there! Sorry you're having trouble. Did you try the solutions that worked for others mentioned here? https://github.com/aaemnnosttv/wp-cli-valet-command/issues/61

**Comment by verstecken** [comment]
It's working. Thanks for your answer. I was missing the right PATH. 
In my case, I think it was also a PHP version problem. I had 8.1. Now I installed php@7.4 with brew and `valet use php@7.4` Thanks again!
