### ISSUE TITLE
Deprecated: ... $longdesc

### ISSUE THREAD

**Issue by fotan** [aaemnnosttv/wp-cli-valet-command#87]
Started getting this error recently on two machines.

`Deprecated: Creation of dynamic property WP_CLI\Dispatcher\Subcommand::$longdesc is deprecated in phar:///opt/homebrew/Cellar/wp-cli/2.7.1/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CompositeCommand.php on line 38`

Tried updating by re-installing wp-cli-valet, not this one is coming up as well.

`Deprecated: Creation of dynamic property WP_CLI\ProcessRun::$caller is deprecated in /Users/danskinem/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/Process/ShellCommand.php on line 60`

Any ideas on how to fix it?  Maybe switch to the dev-master branch?

**Comment by aaemnnosttv** [comment]
Thanks for reporting, I need to revisit this as there are probably a number of maintenance updates that need to be made 👍

**Comment by fotan** [comment]
No worries.  It's a fantastic tool and I really appreciate that you made it.  Saves me a lot of time.

**Comment by aaemnnosttv** [comment]
@duncanheffron I haven't forgotten about it, but #88 is somewhat of a prerequisite here which I had started in the process of addressing this one and need to revisit.

I'm open to a PR to address this specific issue if anyone is eager go have it addressed sooner.

**Comment by aaemnnosttv** [comment]
Seems like this an issue in WP CLI itself that was fixed in https://github.com/wp-cli/wp-cli/pull/5707 and available since WP CLI v2.8.0.
