### ISSUE TITLE
PHP8.2 deprecation notices

### ISSUE THREAD

**Issue by lumpysimon** [aaemnnosttv/wp-cli-valet-command#91]
When running the `wp valet new` command using PHP8.2 the following deprecation warning is shown five times:

`Deprecated: Creation of dynamic property WP_CLI\ProcessRun::$caller is deprecated in /Users/myuserhere/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/Process/ShellCommand.php on line 60`

**Comment by huzaifaalmesbah** [comment]
i also got this issue. i try on php v8.2 and v8.3

<img width="1030" alt="Screenshot 2024-01-21 at 7 22 51 PM" src="https://github.com/aaemnnosttv/wp-cli-valet-command/assets/63150399/6968963a-b4ea-4664-8942-0b747f9fca55">

**Comment by mralaminahamed** [comment]
@aaemnnosttv, have any update for this?

**Comment by aaemnnosttv** [comment]
I haven't had a chance to get to it yet, unfortunately. I'm open to a PR if someone would like to offer a fix?
